import {MigrationInterface, QueryRunner} from 'typeorm';

export class AutoGenerated1515092035006 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE vendor_files DROP FOREIGN KEY `fk_6c3475551cc3e3e5e6fac1569ed`");
        await queryRunner.query("ALTER TABLE vendor_files DROP FOREIGN KEY `fk_cc5a36c56f85fe70f6c5ce6aed3`");
        await queryRunner.query("ALTER TABLE vendor_files CHANGE `fileTypeId` `fileTypeId` int(11)");
        await queryRunner.query("ALTER TABLE vendor_files CHANGE `vendorId` `vendorId` int(11)");
        await queryRunner.query("ALTER TABLE circuit DROP FOREIGN KEY `fk_79b320313e7f85bd71e9bcbfc69`");
        await queryRunner.query("ALTER TABLE circuit CHANGE `sla_latency` `sla_latency` double");
        await queryRunner.query("ALTER TABLE circuit CHANGE `sla_availability` `sla_availability` double");
        await queryRunner.query("ALTER TABLE circuit CHANGE `sla_throughput` `sla_throughput` double");
        await queryRunner.query("ALTER TABLE circuit CHANGE `sla_jitter` `sla_jitter` double");
        await queryRunner.query("ALTER TABLE circuit CHANGE `sla_packet_loss` `sla_packet_loss` double");
        await queryRunner.query("ALTER TABLE circuit CHANGE `cost` `cost` double");
        await queryRunner.query("ALTER TABLE circuit CHANGE `term` `term` int(11)");
        await queryRunner.query("ALTER TABLE circuit CHANGE `capacity` `capacity` double");
        await queryRunner.query("ALTER TABLE circuit CHANGE `creationDate` `creationDate` datetime");
        await queryRunner.query("ALTER TABLE circuit CHANGE `vendorId` `vendorId` int(11)");
        await queryRunner.query("ALTER TABLE device_backup_configuration CHANGE `protocol` `protocol` varchar(255)");
        await queryRunner.query("ALTER TABLE device_backup_configuration CHANGE `port` `port` int(11)");
        await queryRunner.query("ALTER TABLE device_backup_configuration CHANGE `userName` `userName` varchar(255)");
        await queryRunner.query("ALTER TABLE device_backup_configuration CHANGE `password` `password` varchar(255)");
        await queryRunner.query("ALTER TABLE device_backup_configuration CHANGE `enablePassword` `enablePassword` varchar(255)");
        await queryRunner.query("ALTER TABLE global_backup_configuration CHANGE `protocol` `protocol` varchar(255)");
        await queryRunner.query("ALTER TABLE global_backup_configuration CHANGE `port` `port` int(11)");
        await queryRunner.query("ALTER TABLE global_backup_configuration CHANGE `userName` `userName` varchar(255)");
        await queryRunner.query("ALTER TABLE global_backup_configuration CHANGE `password` `password` varchar(255)");
        await queryRunner.query("ALTER TABLE global_backup_configuration CHANGE `enablePassword` `enablePassword` varchar(255)");
        await queryRunner.query("ALTER TABLE vendor_files ADD CONSTRAINT `fk_6c3475551cc3e3e5e6fac1569ed` FOREIGN KEY (`fileTypeId`) REFERENCES `vendor_file_types`(`id`)");
        await queryRunner.query("ALTER TABLE vendor_files ADD CONSTRAINT `fk_cc5a36c56f85fe70f6c5ce6aed3` FOREIGN KEY (`vendorId`) REFERENCES `vendor`(`id`)");
        await queryRunner.query("ALTER TABLE circuit ADD CONSTRAINT `fk_79b320313e7f85bd71e9bcbfc69` FOREIGN KEY (`vendorId`) REFERENCES `vendor`(`id`)");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE circuit DROP FOREIGN KEY `fk_79b320313e7f85bd71e9bcbfc69`");
        await queryRunner.query("ALTER TABLE vendor_files DROP FOREIGN KEY `fk_cc5a36c56f85fe70f6c5ce6aed3`");
        await queryRunner.query("ALTER TABLE vendor_files DROP FOREIGN KEY `fk_6c3475551cc3e3e5e6fac1569ed`");
        await queryRunner.query("ALTER TABLE global_backup_configuration CHANGE `enablePassword` `enablePassword` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL");
        await queryRunner.query("ALTER TABLE global_backup_configuration CHANGE `password` `password` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL");
        await queryRunner.query("ALTER TABLE global_backup_configuration CHANGE `userName` `userName` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL");
        await queryRunner.query("ALTER TABLE global_backup_configuration CHANGE `port` `port` int(11) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE global_backup_configuration CHANGE `protocol` `protocol` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL");
        await queryRunner.query("ALTER TABLE device_backup_configuration CHANGE `enablePassword` `enablePassword` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL");
        await queryRunner.query("ALTER TABLE device_backup_configuration CHANGE `password` `password` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL");
        await queryRunner.query("ALTER TABLE device_backup_configuration CHANGE `userName` `userName` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL");
        await queryRunner.query("ALTER TABLE device_backup_configuration CHANGE `port` `port` int(11) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE device_backup_configuration CHANGE `protocol` `protocol` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL");
        await queryRunner.query("ALTER TABLE circuit CHANGE `vendorId` `vendorId` int(11) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE circuit CHANGE `creationDate` `creationDate` datetime DEFAULT NULL");
        await queryRunner.query("ALTER TABLE circuit CHANGE `capacity` `capacity` double(22) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE circuit CHANGE `term` `term` int(11) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE circuit CHANGE `cost` `cost` double(22) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE circuit CHANGE `sla_packet_loss` `sla_packet_loss` double(22) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE circuit CHANGE `sla_jitter` `sla_jitter` double(22) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE circuit CHANGE `sla_throughput` `sla_throughput` double(22) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE circuit CHANGE `sla_availability` `sla_availability` double(22) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE circuit CHANGE `sla_latency` `sla_latency` double(22) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE circuit ADD CONSTRAINT `fk_79b320313e7f85bd71e9bcbfc69` FOREIGN KEY (`vendorId`) REFERENCES `vendor`(`id`)");
        await queryRunner.query("ALTER TABLE vendor_files CHANGE `vendorId` `vendorId` int(11) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE vendor_files CHANGE `fileTypeId` `fileTypeId` int(11) DEFAULT NULL");
        await queryRunner.query("ALTER TABLE vendor_files ADD CONSTRAINT `fk_cc5a36c56f85fe70f6c5ce6aed3` FOREIGN KEY (`vendorId`) REFERENCES `vendor`(`id`)");
        await queryRunner.query("ALTER TABLE vendor_files ADD CONSTRAINT `fk_6c3475551cc3e3e5e6fac1569ed` FOREIGN KEY (`fileTypeId`) REFERENCES `vendor_file_types`(`id`)");
    }

}
